### ISSUE TITLE
好巧

### ISSUE THREAD

**Issue by quarkape** [JJAYCHEN1e/ecnu-lib-seat-reservation#1]
好巧，我今天也做了一个，不过用的java

**Comment by jjaychen1e** [comment]
~~最近图书馆似乎更换了新的系统，这个脚本应该是不能用了~~

看错了，这是预约位置的脚本（我以为是预约研讨室的

**Comment by quarkape** [comment]
我已收到您的信件，顺颂时祺。

**Comment by quarkape** [comment]
嗯嗯，应该是能用的。不过你在代码里好像把自己学号暴露了，现在有一些接口可以直接根据学号看到学籍头像😳
